Fix container name for DB URI (#87)
The example `ATUIN_DB_URI` uses `@db` as the hostname, but the container
was named `postgresql` which led to connection errors:

```
Location:
    /app/crates/atuin-server/src/lib.rs:143:10
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:****@db/atuindb" }

Caused by:
    Other(error communicating with database: failed to lookup address information: Name or service not known

    Caused by:
        failed to lookup address information: Name or service not known

    Location:
        crates/atuin-server-postgres/src/lib.rs:53:39)

```